# Generated by Django 6.0.4 on 2026-04-18 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_alerta', models.CharField(max_length=20)),
                ('mensaje_estado', models.CharField(max_length=50)),
                ('mensaje_detalle', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reading')),
            ],
        ),
        migrations.CreateModel(
            name='LogConexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_max_peligro', models.FloatField()),
                ('temp_min_precaucion', models.FloatField()),
                ('turbidez_peligro', models.IntegerField()),
                ('turbidez_precaucion', models.IntegerField()),
                ('conductividad_peligro', models.IntegerField()),
                ('conductividad_precaucion', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
        ),
    ]
