# Generated by Django 6.0.4 on 2026-04-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_device_activo_device_mac_address_device_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'verbose_name': 'Lectura', 'verbose_name_plural': 'Lecturas'},
        ),
    ]
