# Generated by Django 5.2.13 on 2026-04-23 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_reading_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-fecha'], 'verbose_name': 'Alerta', 'verbose_name_plural': 'Alertas'},
        ),
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['-fecha'], 'verbose_name': 'Comando', 'verbose_name_plural': 'Comandos'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.AlterModelOptions(
            name='logconexion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Conexión', 'verbose_name_plural': 'Conexiones de registro'},
        ),
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['-fecha'], 'verbose_name': 'Lectura', 'verbose_name_plural': 'Lecturas'},
        ),
        migrations.AlterModelOptions(
            name='threshold',
            options={'verbose_name': 'Umbral', 'verbose_name_plural': 'Umbrales'},
        ),
        migrations.AddField(
            model_name='command',
            name='ejecutado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='threshold',
            name='ph_max_peligro',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='threshold',
            name='ph_max_precaucion',
            field=models.FloatField(default=8.5),
        ),
        migrations.AddField(
            model_name='threshold',
            name='ph_min_peligro',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='threshold',
            name='ph_min_precaucion',
            field=models.FloatField(default=6.0),
        ),
        migrations.AlterField(
            model_name='alert',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='api.device'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='nivel_alerta',
            field=models.CharField(choices=[('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('ROJO', 'Rojo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='api.reading'),
        ),
        migrations.AlterField(
            model_name='command',
            name='command',
            field=models.CharField(choices=[('SINCRONIZAR', 'Sincronizar'), ('ACTIVAR_ALARMA', 'Activar alarma'), ('DESACTIVAR_ALARMA', 'Desactivar alarma'), ('ENCENDER_FILTRADO', 'Encender filtrado'), ('APAGAR_FILTRADO', 'Apagar filtrado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='command',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='api.device'),
        ),
        migrations.AlterField(
            model_name='logconexion',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.device'),
        ),
        migrations.AlterField(
            model_name='logconexion',
            name='evento',
            field=models.CharField(choices=[('CONECTADO', 'Conectado'), ('DESCONECTADO', 'Desconectado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='logconexion',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reading',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='api.device'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='conductividad_peligro',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='conductividad_precaucion',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='umbral', to='api.device'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='temp_max_peligro',
            field=models.FloatField(default=60.0),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='temp_min_precaucion',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='turbidez_peligro',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='turbidez_precaucion',
            field=models.IntegerField(default=300),
        ),
    ]
