# Generated by Django 5.2.13 on 2026-04-25 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_alert_options_alter_command_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='TipoVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de variable',
                'verbose_name_plural': 'Tipos de variables',
            },
        ),
        migrations.RemoveField(
            model_name='command',
            name='device',
        ),
        migrations.RemoveField(
            model_name='logconexion',
            name='device',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='device',
        ),
        migrations.RemoveField(
            model_name='threshold',
            name='device',
        ),
        migrations.AlterModelOptions(
            name='logconexion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Log de conexión', 'verbose_name_plural': 'Logs de conexión'},
        ),
        migrations.AddField(
            model_name='logconexion',
            name='detalle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='logconexion',
            name='evento',
            field=models.CharField(choices=[('CONECTADO', 'Conectado'), ('DESCONECTADO', 'Desconectado'), ('ERROR', 'Error')], max_length=50),
        ),
        migrations.CreateModel(
            name='Actuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('BOMBA', 'Bomba de agua'), ('FILTRO', 'Filtro'), ('ALARMA', 'Alarma'), ('VALVULA', 'Válvula'), ('OTRO', 'Otro')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuadores', to='api.comunidad')),
            ],
            options={
                'verbose_name': 'Actuador',
                'verbose_name_plural': 'Actuadores',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('mac_address', models.CharField(blank=True, max_length=50, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('firmware', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actuador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='api.actuador')),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='api.comunidad')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='ComandoRemoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.CharField(choices=[('SINCRONIZAR', 'Sincronizar'), ('ACTIVAR_ALARMA', 'Activar alarma'), ('DESACTIVAR_ALARMA', 'Desactivar alarma'), ('ENCENDER_FILTRADO', 'Encender filtrado'), ('APAGAR_FILTRADO', 'Apagar filtrado'), ('REINICIAR', 'Reiniciar dispositivo')], max_length=100)),
                ('ejecutado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='api.dispositivo')),
            ],
            options={
                'verbose_name': 'Comando remoto',
                'verbose_name_plural': 'Comandos remotos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='logconexion',
            name='dispositivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.dispositivo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EstadoActuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ENCENDIDO', 'Encendido'), ('APAGADO', 'Apagado'), ('ERROR', 'Error')], default='APAGADO', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='api.actuador')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_actuador', to='api.dispositivo')),
            ],
            options={
                'verbose_name': 'Estado de actuador',
                'verbose_name_plural': 'Estados de actuadores',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('turbidez', models.IntegerField()),
                ('conductividad', models.IntegerField()),
                ('ph', models.FloatField()),
                ('estado', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='api.dispositivo')),
            ],
            options={
                'verbose_name': 'Lectura de sensor',
                'verbose_name_plural': 'Lecturas de sensores',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCalidadAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('VERDE', 'Agua apta'), ('AMARILLO', 'Precaución'), ('ROJO', 'Peligro')], max_length=20)),
                ('mensaje_estado', models.CharField(max_length=100)),
                ('mensaje_detalle', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_calidad', to='api.dispositivo')),
                ('lectura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_calidad', to='api.lecturasensor')),
            ],
            options={
                'verbose_name': 'Estado de calidad del agua',
                'verbose_name_plural': 'Estados de calidad del agua',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_alerta', models.CharField(choices=[('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('ROJO', 'Rojo')], max_length=20)),
                ('mensaje_estado', models.CharField(max_length=100)),
                ('mensaje_detalle', models.CharField(max_length=200)),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='api.comunidad')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='api.dispositivo')),
                ('lectura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='api.lecturasensor')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PuntoMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='api.comunidad')),
            ],
            options={
                'verbose_name': 'Punto de monitoreo',
                'verbose_name_plural': 'Puntos de monitoreo',
            },
        ),
        migrations.CreateModel(
            name='RespuestaComando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exitoso', models.BooleanField(default=False)),
                ('mensaje', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comando', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='api.comandoremoto')),
            ],
            options={
                'verbose_name': 'Respuesta de comando',
                'verbose_name_plural': 'Respuestas de comandos',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('TEMPERATURA', 'Temperatura'), ('TURBIDEZ', 'Turbidez'), ('CONDUCTIVIDAD', 'Conductividad'), ('PH', 'pH'), ('OTRO', 'Otro')], max_length=50)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='api.dispositivo')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
            },
        ),
        migrations.AddField(
            model_name='lecturasensor',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='api.sensor'),
        ),
        migrations.CreateModel(
            name='UmbralCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_max_peligro', models.FloatField(default=60.0)),
                ('temp_min_precaucion', models.FloatField(default=10.0)),
                ('turbidez_peligro', models.IntegerField(default=600)),
                ('turbidez_precaucion', models.IntegerField(default=300)),
                ('conductividad_peligro', models.IntegerField(default=600)),
                ('conductividad_precaucion', models.IntegerField(default=300)),
                ('ph_min_peligro', models.FloatField(default=4.0)),
                ('ph_max_peligro', models.FloatField(default=10.0)),
                ('ph_min_precaucion', models.FloatField(default=6.0)),
                ('ph_max_precaucion', models.FloatField(default=8.5)),
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='umbral', to='api.dispositivo')),
                ('tipo_variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipovariable')),
            ],
            options={
                'verbose_name': 'Umbral de calidad',
                'verbose_name_plural': 'Umbrales de calidad',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='api.comunidad')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALERTA', 'Alerta'), ('INFO', 'Información'), ('ERROR', 'Error')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='api.dispositivo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='comandoremoto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('detalle', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='api.dispositivo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='api.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.usuario')),
            ],
            options={
                'verbose_name': 'Usuario-Rol',
                'verbose_name_plural': 'Usuarios-Roles',
                'unique_together': {('usuario', 'rol')},
            },
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='Command',
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Threshold',
        ),
    ]
